import { BaseColors, FontFamily } from '@config/theme';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    width: '100%',
    backgroundColor: BaseColors.lightBg,
  },
  mainDiv: {
    flex: 1,
    backgroundColor: BaseColors.white,
    paddingVertical: 20,
    marginHorizontal: 20,
    borderRadius: 12,
    marginVertical: 20,
    paddingHorizontal: 25,
    shadowColor: BaseColors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  wordcontainer: {
    width: '60%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 0.5,
  },
  imgContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleText: {
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 40,
    fontFamily: FontFamily.bold,
    color: BaseColors.textColor,
    textAlign: 'center',
  },
  subtitleText: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    marginTop: 15,
    fontFamily: FontFamily.regular,
    color: BaseColors.textColor,
  },
  buttoncontainer: {
    flex: 0.3,
    marginHorizontal: 15,
    justifyContent: 'flex-end',
  },
  textInputContainer: {
    width: '100%',
    height: 150,
    borderWidth: 1,
    borderColor: BaseColors.borderColor,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 5,
  },
  numbercontainer: {
    width: 180,
    height: 90,
    borderRadius: 12,
    borderColor: BaseColors.borderColor,
    borderWidth: 1,
    padding: 24,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInput: {
    flex: 1,
    textAlignVertical: 'top',
    fontSize: 16,
  },
  stop: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: FontFamily.regular,
    color: BaseColors.red,
    textAlign: 'center',
  },
  stopimg: { height: 100, width: 100, marginBottom: 20, alignSelf: 'center' },
});
